### ISSUE TITLE
Any thoughts on Poetry support?

### ISSUE THREAD

**Issue by blarghmatey** [dante-signal31/vdist#4]
Vdist looks like a great tool for packaging apps. I'm curious if you have given any thought to adding support for Poetry as an alternative to PIp when bringing in the Python dependencies? I understand that it has a fairly well designed Python API so it should be fairly straightforward to integrate with it.

**Comment by dante-signal31** [comment]
I didn't know about Poetry. I will think about it in next vdist iterations. It looks like pretty interesting.

I have to assess not only Poetry advantages but how easy is to install it in target distributions vdist offers. 

Thank you very much for your suggestion.

**Comment by dante-signal31** [comment]
[Added Poetry assessment](https://github.com/dante-signal31/vdist/commit/b135f81c01e5bf32b37295a9620274b346271e71) to roadmap

**Comment by blarghmatey** [comment]
So, I just worked through setting up a build using vdist and Poetry. The relevant set of changes was in the debian.sh script. I just added the following lines in place of the step that handles installing from requirements.txt

```
# Get rid of venv in dev environment
find {{package_tmp_root}} -type d -name '.venv' -print0 | xargs -0 rm -rf
find {{package_tmp_root}} -type d -name 'venv' -print0 | xargs -0 rm -rf
# Install package python dependencies inside our portable python environment.
$PIP_BIN install poetry
$PYTHON_BASEDIR/bin/poetry config virtualenvs.create false
$PYTHON_BASEDIR/bin/poetry build
$PIP_BIN install dist/*.whl
```
